### ISSUE TITLE
[BUG] model_transform 에서 이미 fit한 모델임에도 transform이 되지 않는 문제

### ISSUE THREAD

**Issue by seahahn** [AI-Play/ML-Train#38]
### 작성자

안경호

### 1. 버그 내용

```
Traceback (most recent call last):
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 367, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\fastapi\applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  **File "C:\Users\Ahn\projects\AI-Play\ML-Train\.\functions\model_functions.py", line 149, in model_transform
    X = v.transform(X)**
  File "C:\Users\Ahn\anaconda3\envs\mlfuncs\lib\site-packages\category_encoders\one_hot.py", line 246, in transform
    raise ValueError(
**ValueError: Must train encoder before it can be used to transform data.**
```

데이터셋을 집어넣어 fit 완료 후 S3에 저장까지 된 모델인데, 이를 불러와서 transform을 하니 위와 같은 에러가 발생합니다.
현재 S3에 저장된 모델 객체 중 [ahn_new.pickle](https://s3.console.aws.amazon.com/s3/object/aiplay-test-bucket?region=ap-northeast-2&prefix=test/ahn_new.pickle) 을 사용하였습니다.

### 2. 기대 사항

에러 없이 transform한 결과를 return 받아 프론트에서 출력되기를 바랍니다.

### 3-1. 운영체제

윈도우 10

### 3-2. 개발 도구

VSCode

### 3-3. 작업하신 개발 환경을 알려주세요. (다중 선택 가능)

localhost

### 4. 추가 내용

pickle이 아니라 joblib으로 모델 저장/불러오기 모듈을 바꾸는건 어떨까 싶습니다.
구체적인 내용은 다시 검토해봐야 하겠지만, 제 기억에 joblib의 기능과 사용성이 더 좋다고 알고 있습니다.

**Comment by KayyoungHL** [comment]
예외처리가 되어있는데 왜 해당 에러가 발생하는지 모르겠습니다.
에러 재현이 가능하면 같이 확인해 볼 수 있을까요?

**Comment by seahahn** [comment]
> 예외처리가 되어있는데 왜 해당 에러가 발생하는지 모르겠습니다. 에러 재현이 가능하면 같이 확인해 볼 수 있을까요?

fit을 했음에도 훈련되지 않은 모델이라 출력이 되어 에러 확인을 위해 임시로 예외 처리는 제거했구요,
그 결과가 위와 같은 모습입니다.

**Comment by KayyoungHL** [comment]
S3 사용해서 확인해본 결과 정상적으로 결과가 출력되고 있습니다.
현재는 왜 해당 에러가 발생하는 지 알 수 없어 해결을 못하는 상황입니다.
혹시 해당 에러의 재현이 가능하시면, 원인을 파악해 보겠습니다.
